### ISSUE TITLE
Multiple Streams Auth Repeated

### ISSUE THREAD

**Issue by freimer** [Widen/tap-rest-api-msdk#5]
Current PR #4 requires multiple authentication information, per stream.  It is often the case that the authentication information is the same for streams that are grouped together in a project/pipeline, as they often access the same service.  It would be nice to have some flexibility to specify matches of various types for which authentication information is used for which streams.  I propose the following scheme:
```yaml
streams_auth:
  - match_type: exact
    name: stream1234
    headers:
      "X-apiKey": auth1234
  - match_type: prefix
    name: stream_abc_
    headers:
      "X-apiKey": auth_abc1234
  - match_type: suffix
    name: _accounts_
    headers:
      "X-apiKey": auth_acc1234
  - match_type: regex
    name: "^stream_[a-z]+_[0-9]+"
    headers:
      "X-apiKey": auth_re1234
```
The order of the auth info would matter; the first entry that matched is used, and if none match no authentication is assumed.  This can be expanded later to include other authentication types, by adding an `auth_type` in addition or instead of headers and other appropriate keys.
Headers should also be allowed in both the main streams array, as well as streams_auth.  Non-sensitive headers should be specified in streams, and sensitive headers, such as Authorization or X-APIKey, should be specified in streams_auth.
