### ISSUE TITLE
How to specify a path param?

### ISSUE THREAD

**Issue by christophediprima** [Widen/tap-rest-api-msdk#53]
Hi there! Does the plugin have support for path params? I am trying to do something like this but can find no example...

```yaml
plugins:
  extractors:
  - name: tap-rest-api-msdk
    variant: widen
    pip_url: tap-rest-api-msdk
    config:
      streams:
      - name: object_results
        path: /object/{object-id}/results
        params: 
          object-id: OBJECT_ID
```
